apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: dev
  labels:
    app: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: asia-south1-docker.pkg.dev/kubernetes-470606/repos/adservice:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: dev
  labels:
    app: adservice
spec:
  selector:
    app: adservice
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
