apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: dev
  labels:
    app: checkoutservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: asia-south1-docker.pkg.dev/kubernetes-470606/repos/checkoutservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050   # Adjusted to correct port
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: dev
  labels:
    app: checkoutservice
spec:
  selector:
    app: checkoutservice
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP
