apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: dev
  labels:
    app: currencyservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: currencyservice
          image: asia-south1-docker.pkg.dev/kubernetes-470606/repos/currencyservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7000   # Correct port
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              value: "7000"  # Must define this
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: dev
  labels:
    app: currencyservice
spec:
  selector:
    app: currencyservice
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: ClusterIP
