apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: dev
  labels:
    app: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: loadgenerator
          image: asia-south1-docker.pkg.dev/kubernetes-470606/repos/loadgenerator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  namespace: dev
  labels:
    app: loadgenerator
spec:
  selector:
    app: loadgenerator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
