apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: dev
  labels:
    app: recommendationservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: recommendationservice
          image: asia-south1-docker.pkg.dev/kubernetes-470606/repos/recommendationservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: dev
  labels:
    app: recommendationservice
spec:
  selector:
    app: recommendationservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
